version: "3.8"

services:
  backend:
    user: "${UID:-1000}:${GID:-1000}"
    working_dir: /app
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - ./persistance/backend:/.config/psysh
      - ./persistance/composer/repo:/.composer/cache/repo/https---repo.packagist.org/
      - ./persistance/composer/files:/.composer/cache/files/
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "8000:8000"

  database:
    image: postgres:15rc2-alpine3.16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./persistance/database:/var/lib/postgresql/data
